name: "CI - Test Features"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-scenarios:
    runs-on: ${{ matrix.image }}
    continue-on-error: true
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        features:
          - argocd
          - atlas
          - bicep
          - calicoctl
          - cilium
          - clusterctl
          - deno
          - flux
          - gcloud
          - helm
          - istioctl
          - just
          - kind
          - kubebuilder
          - kubectl
          - mongosh
          - pkl
          - pulumi
          - redis
          - ruff
          - spin
          - task
          - terraform
          - uv
          - volta
          - wasm-tools
          - wasmtime
          - wit-bindgen
          - wit-deps
          - zig
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .

  test-global:
    runs-on: ${{ matrix.image }}
    continue-on-error: true
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
