name: "CI - Test Features"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-scenarios:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - argocd
          - bicep
          - binaryen
          - calicoctl
          - cilium
          - clusterctl
          - deno
          - flux
          - func
          - gcloud
          - helm
          - istioctl
          - kind
          - kubebuilder
          - kubectl
          - mkcert
          - pavex
          - pulumi
          - rad
          - spin
          - task
          - wasm-tools
          - wasmtime
          - wit-bindgen
          - wit-deps
          - zig
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated .

  test-global:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing global scenarios"
        run: devcontainer features test --global-scenarios-only .
