name: "PR - Test Features"
on:
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            argocd: ./**/argocd/**
            atlas: ./**/atlas/**
            bicep: ./**/bicep/**
            calicoctl: ./**/calicoctl/**
            cilium: ./**/cilium/**
            clusterctl: ./**/clusterctl/**
            deno: ./**/deno/**
            flux: ./**/flux/**
            gcloud: ./**/gcloud/**
            helm: ./**/helm/**
            istioctl: ./**/istioctl/**
            kind: ./**/kind/**
            kubebuilder: ./**/kubebuilder/**
            kubectl: ./**/kubectl/**
            pulumi: ./**/pulumi/**
            spin: ./**/spin/**
            task: ./**/task/**
            wasm-tools: ./**/wasm-tools/**
            wasmtime: ./**/wasmtime/**
            wit-bindgen: ./**/wit-bindgen/**
            wit-deps: ./**/wit-deps/**
            zig: ./**/zig/**

  test-features:
    needs: [detect-changes]
    runs-on: ${{ matrix.image }}
    continue-on-error: true
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
        baseImage:
          - mcr.microsoft.com/devcontainers/base:bullseye # Debian 11
          - mcr.microsoft.com/devcontainers/base:bookworm # Debian 12
          - mcr.microsoft.com/devcontainers/base:jammy # Ubuntu 22.04
          - mcr.microsoft.com/devcontainers/base:noble # Ubuntu 24.04
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-scenarios:
    needs: [detect-changes]
    runs-on: ${{ matrix.image }}
    continue-on-error: true
    strategy:
      matrix:
        image:
          - ubuntu-24.04
          - ubuntu-24.04-arm
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v4

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated  .
